apiVersion: v1
kind: Service
metadata:
  name: simple
  labels:
    app: simple
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http-service
  selector:
    app: simple
  sessionAffinity: None
