apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: simple-servicemonitor
  labels:
    name: simple
    collectMetrics: "true"
spec:
  endpoints:
  - port: http
    path: /-/metrics
    interval: 30s
  selector:
    matchLabels:
      app: simple
